### ISSUE TITLE
Figure out how to get it to work with jsdom

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/fast-cli#2] opened 2016-05-18 22:11 UTC
Would be much more lightweight using [jsdom](https://github.com/tmpvar/jsdom) than the current PhantomJS setup.

This is how far I got. Currently only returns `0`, which means the JS on the site is never run for some reason.

``` js
'use strict';
const jsdom = require('jsdom');

jsdom.env({
    url: 'http://fast.com/',
    scripts: ['http://code.jquery.com/jquery.js'],
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36',
    strictSSL: false,
    features: {
        FetchExternalResources: ['script'],
        ProcessExternalResources: ['script']
    },
    done: (err, window) => {
        if (err) {
            throw err;
        }

        setTimeout(() => {
            console.log('Speed:', window.$('#speed-value').text().trim(), window.$('#speed-units').text().trim());
        }, 5000);
    }
});
```
## 

Help appreciated 😀

**Comment by AdriVanHoudt** [comment] 2016-05-19 07:19
shouldn't you add "link" to `FetchExternalResources` ?

**Comment by imvetri** [comment] 2016-05-19 07:28
I tried adding link to  `FetchExternalResources: ['script'],` as suggested by someone here(I couldnt see that comment anymore) But that didnt work either.


`window.$('#speed-value').text().trim() -> returns 0 ` no matter how long the timeout is. I am suspecting that javascript inside the document isnt getting executed. Working on this

**Comment by AdriVanHoudt** [comment] 2016-05-19 07:30
@imvetri I commented and then realised the js is not loaded via link tags :D 
maybe listening for errors will result in something if not tried already? https://github.com/tmpvar/jsdom#listening-for-script-errors-during-initialization

**Comment by imvetri** [comment] 2016-05-19 07:35
@AdriVanHoudt Thanks :D 

I am currently testing above scenario with a local file. I will post my findings.

**Comment by imvetri** [comment] 2016-05-19 10:43
Not sure whether this is helpful or not, 

jsdom doesnt work well when page has XHR requests going on.

for more details, please refer here https://github.com/sinonjs/sinon/issues/657

the issue is created on 2012 year. I couldnt investigate further. Please ignore if this isnt helping

**Comment by Sebmaster** [comment] 2016-05-19 13:09
I debugged the thing that's blocking this (tmpvar/jsdom#1491), but even when hacking around that, it seems that the speed we can get with jsdom is much lower than what some connections will provide. Testing around a bit, I seem to get around ~50Mbps, even though I should be getting 150 if I open the page in a browser.

Maybe I'll get some time to check where we're loosing all this speed someday(TM).

**Comment by sindresorhus** [comment] 2016-07-10 23:37
I tried it out with latest `jsdom` and works now, but the speed is totally off. I'm on a 100Mbps connection, which `fast-cli` correctly identifies, but when running it with JSDOM, I get 17Mbps.

**Comment by MarkTiedemann** [comment] 2017-04-15 16:52
How about using [Headless Chromium](https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md) for the speed testing? :)

**Comment by sindresorhus** [comment] 2017-04-16 05:13
That would be better than PhantomJS, but I'm waiting for someone to wrap it in a npm package so it *just works*.

**Comment by mcpherson** [comment] 2017-06-08 15:35
Don't know if it acceptable practice to post this comment here, but since this is where I landed looking for info related to fast-cli and PahntomJS...

`npm` installation fails on Raspberry PI (3) due to no native ARM PhantomJS. I attempted to compile based on the instructions at the PhantomJS site and it failed in an ugly fashion:

```sh
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Makefile.WebCore.Target:47888: recipe for target '.obj/page/DOMWindow.o' failed
make[2]: *** [.obj/page/DOMWindow.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/pippipi/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile.WebCore:68: recipe for target 'sub-Target-pri-make_first-ordered' failed
make[1]: *** [sub-Target-pri-make_first-ordered] Error 2
make[1]: Leaving directory '/home/pippipi/phantomjs/src/qt/qtwebkit/Source/WebCore'
Makefile:177: recipe for target 'sub-Source-WebCore-WebCore-pro-make_first-ordered' failed
make: *** [sub-Source-WebCore-WebCore-pro-make_first-ordered] Error 2

ERROR: Failed to build PhantomJS! Building Qt WebKit failed.
```

**Closed** 2017-09-24 18:49 UTC
Labels: blocked, enhancement, help wanted
